name: Sync to HuggingFace Space

on:
  push:
    branches: [main]

jobs:
  sync-to-huggingface:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HuggingFace Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub Actions"
          git remote add hfspace https://freddy-jmdataai:$HF_TOKEN@huggingface.co/spaces/freddy-jmdataai/leadgen-api
          git push hfspace main --force
